# Generated by Django 5.2.2 on 2025-06-19 09:32

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haircuts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='gallery'),
        ),
    ]
